name: GitHub_Actions_run_tests

on:
  push:
    branches:
      -main
      
jobs:
  run_test:
    runs-on: windows
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start tests
      run: |
        pytest --alluredir report test_main_page.py
    - name: Run report
      run: |
        allure serve report/
